# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.19.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.19.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/aarna/devel/ds-algos

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/aarna/devel/ds-algos

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.19.3/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.19.3/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.19.3/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.19.3/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.19.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.19.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.19.3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.19.3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.19.3/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aarna/devel/ds-algos/CMakeFiles /Users/aarna/devel/ds-algos//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aarna/devel/ds-algos/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f googletest-1.10.x/googlemock/CMakeFiles/gmock.dir/build.make googletest-1.10.x/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest-1.10.x/googlemock/CMakeFiles/gmock_main.dir/build.make googletest-1.10.x/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f googletest-1.10.x/googletest/CMakeFiles/gtest_main.dir/build.make googletest-1.10.x/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f googletest-1.10.x/googletest/CMakeFiles/gtest.dir/build.make googletest-1.10.x/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named bsearch

# Build rule for target.
bsearch: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bsearch
.PHONY : bsearch

# fast build rule for target.
bsearch/fast:
	$(MAKE) $(MAKESILENT) -f src/algorithms/CMakeFiles/bsearch.dir/build.make src/algorithms/CMakeFiles/bsearch.dir/build
.PHONY : bsearch/fast

#=============================================================================
# Target rules for targets named deadlock

# Build rule for target.
deadlock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 deadlock
.PHONY : deadlock

# fast build rule for target.
deadlock/fast:
	$(MAKE) $(MAKESILENT) -f src/algorithms/CMakeFiles/deadlock.dir/build.make src/algorithms/CMakeFiles/deadlock.dir/build
.PHONY : deadlock/fast

#=============================================================================
# Target rules for targets named mutexes

# Build rule for target.
mutexes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mutexes
.PHONY : mutexes

# fast build rule for target.
mutexes/fast:
	$(MAKE) $(MAKESILENT) -f src/algorithms/CMakeFiles/mutexes.dir/build.make src/algorithms/CMakeFiles/mutexes.dir/build
.PHONY : mutexes/fast

#=============================================================================
# Target rules for targets named raii_thread

# Build rule for target.
raii_thread: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raii_thread
.PHONY : raii_thread

# fast build rule for target.
raii_thread/fast:
	$(MAKE) $(MAKESILENT) -f src/algorithms/CMakeFiles/raii_thread.dir/build.make src/algorithms/CMakeFiles/raii_thread.dir/build
.PHONY : raii_thread/fast

#=============================================================================
# Target rules for targets named llist

# Build rule for target.
llist: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 llist
.PHONY : llist

# fast build rule for target.
llist/fast:
	$(MAKE) $(MAKESILENT) -f src/ds/CMakeFiles/llist.dir/build.make src/ds/CMakeFiles/llist.dir/build
.PHONY : llist/fast

#=============================================================================
# Target rules for targets named DataStructures

# Build rule for target.
DataStructures: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DataStructures
.PHONY : DataStructures

# fast build rule for target.
DataStructures/fast:
	$(MAKE) $(MAKESILENT) -f src/ds/CMakeFiles/DataStructures.dir/build.make src/ds/CMakeFiles/DataStructures.dir/build
.PHONY : DataStructures/fast

#=============================================================================
# Target rules for targets named SPSCIntQueue

# Build rule for target.
SPSCIntQueue: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SPSCIntQueue
.PHONY : SPSCIntQueue

# fast build rule for target.
SPSCIntQueue/fast:
	$(MAKE) $(MAKESILENT) -f src/ds/LockFree/CMakeFiles/SPSCIntQueue.dir/build.make src/ds/LockFree/CMakeFiles/SPSCIntQueue.dir/build
.PHONY : SPSCIntQueue/fast

#=============================================================================
# Target rules for targets named evenOddPrinter

# Build rule for target.
evenOddPrinter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 evenOddPrinter
.PHONY : evenOddPrinter

# fast build rule for target.
evenOddPrinter/fast:
	$(MAKE) $(MAKESILENT) -f src/programs/CMakeFiles/evenOddPrinter.dir/build.make src/programs/CMakeFiles/evenOddPrinter.dir/build
.PHONY : evenOddPrinter/fast

#=============================================================================
# Target rules for targets named LinkedListTests

# Build rule for target.
LinkedListTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LinkedListTests
.PHONY : LinkedListTests

# fast build rule for target.
LinkedListTests/fast:
	$(MAKE) $(MAKESILENT) -f test/LinkedListTests/CMakeFiles/LinkedListTests.dir/build.make test/LinkedListTests/CMakeFiles/LinkedListTests.dir/build
.PHONY : LinkedListTests/fast

#=============================================================================
# Target rules for targets named StackWListTests

# Build rule for target.
StackWListTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 StackWListTests
.PHONY : StackWListTests

# fast build rule for target.
StackWListTests/fast:
	$(MAKE) $(MAKESILENT) -f test/StackWListTests/CMakeFiles/StackWListTests.dir/build.make test/StackWListTests/CMakeFiles/StackWListTests.dir/build
.PHONY : StackWListTests/fast

#=============================================================================
# Target rules for targets named SmartPointerTests

# Build rule for target.
SmartPointerTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SmartPointerTests
.PHONY : SmartPointerTests

# fast build rule for target.
SmartPointerTests/fast:
	$(MAKE) $(MAKESILENT) -f test/SmartPointerTests/CMakeFiles/SmartPointerTests.dir/build.make test/SmartPointerTests/CMakeFiles/SmartPointerTests.dir/build
.PHONY : SmartPointerTests/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... DataStructures"
	@echo "... LinkedListTests"
	@echo "... SPSCIntQueue"
	@echo "... SmartPointerTests"
	@echo "... StackWListTests"
	@echo "... bsearch"
	@echo "... deadlock"
	@echo "... evenOddPrinter"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... llist"
	@echo "... mutexes"
	@echo "... raii_thread"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

